### ISSUE TITLE
is there any app.on('disconnect') event ?

### ISSUE THREAD

**Issue by ssh713** [feathersjs/docs#1271] opened 2019-02-18 07:45 UTC
### Comment

I am wondering if there is anything similar to app.on('disconnect', ) event. In the context of chat app how can we let participants know of someone who has disconnected ? There is logout event but there could be other scenarios e.g. loss of internet connection where other clients may want to know if a connection has become offline.

**Comment by daffl** [comment] 2019-03-10 16:37
Duplicate of https://github.com/feathersjs/feathers/issues/1243

**Closed by daffl** 2019-03-10 16:37 UTC
