### ISSUE TITLE
Search is broken on docs site

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/docs#564] opened 2017-04-30 22:53 UTC
<img width="1072" alt="screen shot 2017-04-30 at 3 52 32 pm" src="https://cloud.githubusercontent.com/assets/1571918/25568683/17c6b2dc-2dbd-11e7-9dc4-2dd5d82cf31c.png">

I'm pretty sure something should come up for the query `auth`. Regardless, based off the output, it seems to be ignoring characters after the first.

**Comment by daffl** [comment] 2017-05-01 04:21
Confirmed. This is the error being thrown:

<img width="855" alt="screen shot 2017-04-30 at 9 19 53 pm" src="https://cloud.githubusercontent.com/assets/338316/25571968/ced058c0-2dea-11e7-91f1-bbfddd772c26.png">

**Comment by teddy-error** [comment] 2017-05-17 17:59
Sometimes it just doesn't work at all. It also doesn't clear the blue when you exit the search box or even navigate to a new page.

**Comment by marshallswain** [comment] 2017-05-22 17:26
This is a GitBook issue.  I couldn't figure out which version of gitbook we're using.  Similar issue: https://github.com/GitbookIO/gitbook/issues/497

**Comment by daffl** [comment] 2017-08-16 16:21
Maybe switching to something like https://www.npmjs.com/package/gitbook-plugin-algolia might be the better way to solve this.

**Comment by daffl** [comment] 2017-09-16 19:49
My suspicion is that this is because of emoticon in the text but I am not sure. I have disabled search for now.

**Comment by petermikitsh** [comment] 2017-09-16 20:23
I actually just used search this morning -- it worked after the first character. You need to type in two characters or more. Was on latest chrome, not sure if issues remain for other browsers.

**Comment by daffl** [comment] 2017-09-16 20:36
@petermikitsh Did you see the error?

**Comment by petermikitsh** [comment] 2017-09-16 20:37
Didn't have the console open :(

The UI looked similar to what @teddy-error's screenshot shows after the first letter is typed -- second+ characters began to populate search results.

**Comment by teddy-error** [comment] 2017-11-06 20:01
[Other FOSS projects appear to be using the search plugin without issue](https://github.com/Vue-cd/vue_all/blob/b588d0082f3a4997c6dcc66a276fe8610274a6d6/vuex%2B/docs/book.json). This may suggest that our documentation has some unique trait(s) which are causing the issues.

**Comment by daffl** [comment] 2017-11-06 20:25
Probably. As I mentioned, so far at least the page at https://docs.feathersjs.com/guides/about/vs.html is causing this issue.

**Comment by teddy-error** [comment] 2017-11-06 21:14
I was able to resolve the issue and will create a pull request shortly.

**Comment by teddy-error** [comment] 2017-11-06 21:44
These changes alleviate some of the major annoyances with searching including the exceptions mentioned above. However, there are still some minor quirks present in the functionality. I believe they are caused somehow by `feathers-versions` as removing the plugin will also remedy the quirks.

**Comment by daffl** [comment] 2017-11-06 22:02
What specifically are those quirks? I don't think the version dropdown does anything search related does it?

**Comment by teddy-error** [comment] 2017-11-06 22:16
I was experiencing an issue where a search would not cancel and leave the page in a search state rather than the normal state. E.g: After deleting the text and leaving the box I would still be at `/[somepage]?q=` instead of the page I initiated I initiated the search from `/[somepage]` 

BUT I'm not able to replicate this now. It's possible I accidentally observed the issue at docs.feathersjs.com rather than the test page so:

I am *no longer observing issues with the search*.

**Comment by daffl** [comment] 2017-11-06 22:57
Verified that this is fixed now via https://github.com/feathersjs/docs/pull/907 by @teddy-error  🎉

**Closed by daffl** 2017-11-06 22:57 UTC
